services:
  api:
    build:
      context: api
      dockerfile: dockerfile
      target: dev
    container_name: devops_api
    env_file:
      - .env.api
    ports:
      - "8080:8080"
      - "5005:5005"
    develop:
      watch:
        - action: rebuild
          path: ./api/pom.xml
        - action: sync+restart
          path: ./api/src
          target: /app/src
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: client
      dockerfile: dockerfile
      target: dev
    container_name: devops_client
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /app/src
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
    env_file:
      - .env.client
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: gamificacao_postgres
    restart: always
    environment:
      POSTGRES_DB: devops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

