spring.application.name=gamificacao.grupo-7
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://postgres:5432/${POSTGRES_DB:devops}}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
